name: iom-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - joblib
  - python-dotenv
  - notebook
  - jupyterlab
  - ipywidgets
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scipy
  - scikit-learn
  - scikit-optimize
  - pip:
    - bia-bob
    - torch
    - torchvision

variables:
  BLABLADOR_API_KEY: "my_api_key"
