name: iom-env-torch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.4
  - pip
  - czifile
  - dask
  - ipykernel
  - ipywidgets
  - joblib
  - jupyterlab
  - matplotlib
  - notebook
  - numcodecs
  - numpy
  - pandas
  - plotly
  - polars
  - pyocclient
  - python-dotenv
  - pytorch
  - ray-all
  - scipy
  - scikit-image
  - scikit-learn
  - scikit-optimize
  - seaborn
  - sphinx
  - stackview
  - tabulate
  - torchvision
  - tqdm
  - zarr
  - pip:
    - bia-bob

variables:
  BLABLADOR_API_KEY: "my_api_key"
